version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: open-data-quality
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5430:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    environment:
      DB_USER: postgres
      DB_PASSWORD: open-data-quality
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/open-data-quality
    ports:
      - "3000:3000"
    environment:
      REACT_APP_SERVER_HOST: backend
      REACT_APP_SERVER_PORT: 5000
    depends_on:
      - backend
    networks:
      - app-network

  script:
    build:
      context: ./script
    environment:
      PYTHONUNBUFFERED: 1
      DB_USER: postgres
      DB_PASSWORD: open-data-quality
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      SCRIPT_START_TIME: 1
      SCRIPT_END_TIME: 23
      SCRIPT_SCRAPING_DURATION_MINUTES: 1
      SCRIPT_QUALITY_DURATION_MINUTES: 30
      SCRIPT_PAUSE_DURATION_MINUTES: 30
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
